language: java

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew
  - touch ~/.gradle/gradle.properties && echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties

script:
  - ./gradlew --daemon clean javadoc
  - ./gradlew --daemon test -Ptags="CI"
  - ./gradlew --daemon copyAllureCategories allureReport
  - ./gradlew --daemon jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - aplikat@gmail.com
    on_success: always # default: change
    on_failure: always # default: always